### ISSUE TITLE
when inserting a youtubelink there is an error

### ISSUE THREAD

**Issue by littlefico** [flopana/Simple-YouTube-Downloader#4]
i like the easy design of your code but i does not work
please check with a link
thank you

**Comment by flopana** [comment]
hey sorry for the late response but I do not develop this downloader on github but rather my private gitlab.
https://gitlab.aptinstall.de/flopana/Simple-YouTube-Downloader

**Comment by flopana** [comment]
> hey sorry for the late response but I do not develop this downloader on github but rather my private gitlab.
> https://gitlab.aptinstall.de/flopana/Simple-YouTube-Downloader

Edit I just pushed everything also to github enjoy :)
